export * from "./Dashboard"
export * from "./Auth"
export * from "./ParamaterSetting"
export * from "./OrderDetails"
export * from "./ManufacturingReport"
export * from "./WorkerManager"
export * from "./NotFound"
export * from "./LineOverview"
// export * from "./MachineOverview"
// export * from "./PropertiesMachine"
// export * from "./PropertiesMFC"
// export * from "./PropertiesReport"
// export * from "./PropertiesStatus"
// export * from "./SettingMFC"
// export * from "./HistoryBugs"
export * from "./ManagerSetting/SETTINGAccount"
export * from "./ManagerSetting/SETTINGRole"
export * from "./ManagerSetting/SETTINGUser"
export * from "./ManagerSetting/SETTINGPage"
export * from "./UpdatedData"
