import * as Pages from "@/pages"
import { paths } from "@/config"

const routes = [
    {
        path: paths.dashboard,
        title: "Tổng quan",
        component: Pages.Dashboard,
        mainLayout: null,
        addLayout: "add",
        protected: true,
    },
    {
        path: paths.login,
        title: null,
        component: Pages.Login,
        layout: null,
    },
    {
        path: paths.logout,
        title: null,
        component: Pages.Logout,
        layout: null,
    },
    {
        path: paths.signInOidc,
        title: null,
        component: Pages.SignInOidc,
        layout: null,
    },
    {
        path: paths.setting.account,
        title: "Tài khoản",
        component: Pages.SETTINGAccount,
        mainLayout: null,
        addLayout: "add",
        protected: true,
    },
    {
        path: paths.setting.user,
        title: "QUẢN LÝ NHÂN VIÊN",
        component: Pages.SETTINGUser,
        mainLayout: null,
        addLayout: "add",
        protected: true,
    },
    {
        path: paths.setting.page,
        title: "QUẢN LÝ PHÂN QUYỀN THAO TÁC",
        component: Pages.SETTINGPage,
        mainLayout: null,
        addLayout: "add",
        protected: true,
    },
    {
        path: paths.setting.role,
        title: "QUẢN LÝ CHỨC VỤ",
        component: Pages.SETTINGRole,
        mainLayout: null,
        addLayout: "add",
        protected: true,
    },
    {
        path: "*",
        component: Pages.NotFoundPage,
        layout: null,
    },
    {
        path: paths.paramaterSetting,
        title: "Thông tin lệnh sản xuất",
        component: Pages.ParamaterSetting,
        mainLayout: null,
        addLayout: "add",
        protected: true,
    },
    {
        path: paths.orderDetails + "/:workOrderId/",
        title: "Thông tin chi tiết lệnh sản xuất",
        component: Pages.OrderDetails,
        mainLayout: null,
        addLayout: "add",
        protected: true,
    },
    {
        path: paths.manufacturingReport,
        title: "Báo cáo sản xuất",
        component: Pages.ManufacturingReport,
        mainLayout: null,
        addLayout: "add",
        protected: true,
    },
    {
        path: paths.chiefManufacturingReport,
        title: "Báo cáo sản xuất - Trưởng line",
        component: Pages.ChiefManufacturingReport,
        mainLayout: null,
        addLayout: "add",
        protected: true,
    },
    {
        path: paths.productivityReport,
        title: "Báo cáo lệnh sản xuất theo ngày",
        component: Pages.ProductivityReport,
        mainLayout: null,
        addLayout: "add",
        protected: true,
    },
    {
        path: paths.workerList,
        title: "Nhân viên nhà máy",
        component: Pages.WorkerManager,
        mainLayout: null,
        addLayout: "add",
        protected: true,
    },
    // {
    //     path: paths.settingMFC + "/:lineId" + "/:stationId",
    //     title: "Cài đặt thông số MFC",
    //     component: Pages.SettingMFC,
    //     mainLayout: "main",
    //     addLayout: null,
    //     protected: true,
    // },
    // {
    //     path: paths.historyBugs + "/:lineId" + "/:stationId",
    //     title: "Lịch sử lỗi",
    //     component: Pages.HistoryBugs,
    //     mainLayout: "main",
    //     addLayout: null,
    //     protected: true,
    // },
    {
        path: paths.lineOverview + "/:lineId",
        title: "Giám sát dây chuyền sản xuất",
        component: Pages.LineOverview,
        mainLayout: null,
        addLayout: "add",
        protected: true,
    },
    // {
    //     path: paths.machineOverview + "/:lineId",
    //     title: "Các máy trong dây chuyền sản xuất",
    //     component: Pages.MachineOverview,
    //     mainLayout: null,
    //     addLayout: "add",
    //     protected: true,
    // },
    // {
    //     path: paths.propertiesMachine + "/:lineId" + "/:stationId",
    //     title: "Thông số hoạt động",
    //     component: Pages.PropertiesMachine,
    //     mainLayout: "main",
    //     addLayout: null,
    //     protected: true,
    // },

    // {
    //     path: paths.propertiesMFC + "/:lineId" + "/:stationId",
    //     title: "Thông số MFC",
    //     component: Pages.PropertiesMFC,
    //     mainLayout: "main",
    //     addLayout: null,
    //     protected: true,
    // },
    // {
    //     path: paths.propertiesReport + "/:lineId" + "/:stationId",
    //     title: "Lịch sử hoạt động",
    //     component: Pages.PropertiesReport,
    //     mainLayout: "main",
    //     addLayout: null,
    //     protected: true,
    // },
    // {
    //     path: paths.propertiesStatus + "/:lineId" + "/:stationId",
    //     title: "Lịch sử trạng thái máy",
    //     component: Pages.PropertiesStatus,
    //     mainLayout: "main",
    //     addLayout: null,
    //     protected: true,
    // },
    {
        path: paths.updatedData,
        title: "Nhập thông tin sản xuất",
        component: Pages.UpdatedData,
        mainLayout: null,
        addLayout: "add",
        protected: true,
    },
]
export default routes
